### ISSUE TITLE
I cannot install this piece of software and i cannot find any detailed docs please help 

### ISSUE THREAD

**Issue by talalsamih** [moviemasher/moviemasher.js#1]

**Comment by syntropo** [comment]
This piece of software is typically deployed within the angular-moviemasher project, which has more specific instructions. What exactly are you trying to accomplish?

**Comment by padster2015** [comment]
I had mis understood the documentation in docker hub i don't know i needed both. was causing me a headache but figured it and now big fan of this!

**Comment by syntropo** [comment]
Great - I'm glad you worked it out and are enjoying the projects
