### ISSUE TITLE
how to keep original video quality / dimensions?

### ISSUE THREAD

**Issue by think-01** [moviemasher/moviemasher.js#10]
I wish my output video to have the same dimensions as original. How can I do that? If I ommit 'dimensions' setting for output in export job transcoder resizes everything to some default size, if I set it it obviously resizes everything to the size I've set but how to make it remain unchanged?

Is there any way to get source video dimensions in import callback for example?

**Comment by syntropo** [comment]
Sorry for the delay getting back to you! Within the import complete callback, you should be able to reference `{job.inputs.0.dimensions}` to get the dimensions of visual media.
