### ISSUE TITLE
mmPlayer frame navigation methods

### ISSUE THREAD

**Issue by think-01** [moviemasher/moviemasher.js#12]
what are the frame navigation methods for moviemasher.js? I mean something like gotoAndStop(f) / gotoAndPlay(f) etc.?

**Comment by syntropo** [comment]
You can go to a particular frame by setting the `frame` property of the player. This value is in the frame rate of the player - if you have a frame in different rate you can set the `time` of the player to a TimeRange (which includes rate) and it will be calculated to the nearest frame.
