### ISSUE TITLE
webm and ogg export

### ISSUE THREAD

**Issue by think-01** [moviemasher/moviemasher.js#14]
is there a way to produce webm and ogg files from a mash with masher transcoder? will it work if I send webm/ogg in output object 'extension' field or should I use some specific video codec or something?
Thanks!

**Comment by syntropo** [comment]
I'm not sure offhand what file extension you'd use - whatever would normally be passed to FFmpeg. You'd change the `export_extension` option in moviemasher.ini and likely also adjust `export_video_codec` to remove mp4 specific settings and add any required by your chosen video encoder. To select ogg for audio encoding within videos change `export_audio_codec` (`export_audio_codec_audio` is for audio in audio only files).
