### ISSUE TITLE
getting a current frame graphics data

### ISSUE THREAD

**Issue by think-01** [moviemasher/moviemasher.js#15]
lets say we have a mash and a player paused in particular frame - how can I get to the current bitmap data of clips visible on scene?

I mean, I know I can do:

```
pt.getCurrentUrls = function( )
  {
    var clips;
    clips = Mash.range_clips(this.__mash, this.__time, false);
    return Mash.urls_for_clips_by_type(this.__mash, clips, this.__time);
  };
```

inside Player object definition however I wish to do it without a need to modify moviemasher.js file is that possible? ( Mash is obviously not visible outside due to the module definition style )

**Comment by syntropo** [comment]
Darn, I've been meaning to make all the objects accessible from MovieMasher, like Constant and Colors are - happy to do that, but it won't make its way into the AMI in Amazon for a while...
