### ISSUE TITLE
how to set output file metadata on s3 bucket?

### ISSUE THREAD

**Issue by think-01** [moviemasher/moviemasher.js#16]
I'm sending a job to masher transcoder AMI with a destination pointing to the s3 bucket i.e.:

```
                                    'bucket'    => $S3_BUCKET,
                                    'type'      => 's3',
                                    'region'    => $S3_REGION,
                                    'path'      => "public/videos"
```

how can I set metadata to the video file being created on s3 i.e.:

![image](https://cloud.githubusercontent.com/assets/8135323/21550636/c1e0de4a-cdfb-11e6-9caf-06867b6d6ff9.png)

**Comment by syntropo** [comment]
You can set a limited number of S3 options in the output object (not the destination), but there is no generalized support for metadata. The `mime_type` property should populate the Content-Type. Within the destination you can set `acl`, which controls the permissions. I don't believe there is any support for setting the Cache-Control header - it might be easiest to set that within the callback?
