### ISSUE TITLE
Trying to  load mashes

### ISSUE THREAD

**Issue by Hackarrin** [moviemasher/moviemasher.js#17]
Hi Dan,
I have movie masher installed on amazon at  ec2-54-92-237-232.compute-1.amazonaws.com.
1. I wanna be able to pull up a particular mash via url.
2. What is the default username and password to login to the server 'cos I would like to customize the ui?How do I authenticate into the server using putty.
3. I also wanna figure out how to port my authentication code (written for version 3) to version 4. Please see zipped folder.
[to_dan.zip](https://github.com/moviemasher/moviemasher.js/files/692888/to_dan.zip)

4. Where are the mashes stored 'cos they arent stored in the user folder as in version 3.

I would appreciate it if you could help me out.
Thanks!

**Comment by syntropo** [comment]
I'm assuming you've launched version 4 on a single instance in AWS... 

1. There is no inbuilt support for loading a particular mash via URL, though you could do it from JavaScript - perhaps add a feature request here on GitHub

2. Most any username is valid - the password is the EC2 Instance ID

3. Take a look at authutils.php script - every authentication related function is defined there.

4. They are stored in whatever directory is set in `user_data_directory` in the moviemasher.ini file - I believe the default in your configuration is `/var/www/user-data`

**Comment by Hackarrin** [comment]
Thanks, Dan..
Could you put me through how to get that using javascript?

**Comment by Hackarrin** [comment]
What I actually meant in the second question I posted was find a way to get into the amazon instance id cos Ive tried logging in using putty 'username=root@54.92.237.232' and uploaded my putty generated private key but still doesnt work..

Your help is highly appreciated.

**Comment by syntropo** [comment]
You'll want to load the mash and parse as JSON, then `MovieMasher.player(0).mash = {...}` 

Regarding SSH, you should check up on the EC2 documentation. The instance needs to be started with a key pair assigned, then you use the private portion to gain access along with the `ec2-user` username.
