### ISSUE TITLE
Please, add these to MovieMasher

### ISSUE THREAD

**Issue by ghost** [moviemasher/moviemasher.js#18]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I would like to suggest some features for MovieMasher, here they are:
reverse play (plays a video from end to start)
flip video (horizontally and/or vertically)
transform video (rotate, translate, scale - in every case, a background color/image/video should be set for blank areas)
custom transitions (let a grayscale image/animation represent 2 videos: black: video1, white: video2. The user draws an image/animation in a grayscale shade and the gray intensity up to 255 represents the alpha for video1, while the intensity from 255 to 0 represents the alpha for video2. This way, any transition could be made, even with blending, without hardcoding various transitions)
free transform video (skew, shear and cage distort videos - again, a background color/image/video should be set for blank areas)
video placeholders (enable a video/image as background and place video placeholders to render them on that, either just masked or transformed)

Thanks in advance for any help.

Bye, Ivano.

**Comment by syntropo** [comment]
Thanks for the feature requests - all great ideas.

**Comment by ghost** [comment]
Will these be implemented?

**Comment by ghost** [comment]
Oh, I was forgotting, please also add:
enable animations for transform
enable blending modes for videos
enable filters for videos

**Comment by syntropo** [comment]
This might be implemented at some point - development time for new features is limited. There are already blend modes for video and effects as well. Not sure what is meant by 'animations for transform'.
