### ISSUE TITLE
Using with plain HTML

### ISSUE THREAD

**Issue by ghost** [moviemasher/moviemasher.js#19]
Hello there again.
Is it possible to use MovieMasher with just plain HTML?

Thanks in advance for any help.

Bye, Ivano.

**Comment by ghost** [comment]
I tried it with Firefox and it works without any server or other frameworks.
Unfortunately, it doesn't work on Chrome.

Thanks anyhow.

**Comment by syntropo** [comment]
I just tested again on Chrome and it seems to be working okay - what was your experience? It will not run locally due to the way we're drawing images and such into the canvas.

**Comment by ghost** [comment]
Running locally on Firefox works, running locally on Chrome shows script updates when adding stuff, but nothing is shown when clicking on play/pause.
Edit: Running on webserver with Chrome works ok.
