### ISSUE TITLE
Mirgration vom XML to JSON

### ISSUE THREAD

**Issue by Iceman1975** [moviemasher/moviemasher.js#2]
Is the mirgration guide for old xml files to new json files available? Does the new implementation cover all features of the old php implemetation?

Best regards,
Peter

**Comment by syntropo** [comment]
No to both, I'm sorry to say. It would not be impossible to write a converter, so long as the mashes didn't contain effects that are no longer supported. The syntax is very different though, since JSON is so different from XML.

**Comment by Iceman1975** [comment]
hm, we use still the old version of moviemasher (i.e amazon cloud server). So far the server is a black box. I've a little bit a bad feeling about this. Especially we can't do any update and patches. So the migration to the new version would solve this problem. But it seems not that easy... Is there any possibility to access the amazon instance? Is the code/installation of the moviemasher server anywhere available?

**Comment by syntropo** [comment]
Instances made from the new AMI in EC2 are completely accessible. All of the code in the system is part of one git repository or another. All the repositories are also in docker, so could be explored locally too without involving AWS.
