### ISSUE TITLE
Can we edit the UI of movie masher and integrate the movie masher component in our react project?

### ISSUE THREAD

**Issue by junaidhashtagdev** [moviemasher/moviemasher.js#32]

**Comment by syntropo** [comment]
Yes you can - follow the links to the documentation in the README

**Comment by junaidhashtagdev** [comment]
Like if I just want to add the track panel of movie masher in my app and not use the rest of the movie masher component in our app, would that be possible?

**Comment by syntropo** [comment]
By 'track panel' I'm assuming you mean the Timeline? I'm not sure what value it would have on its own and this hasn't been tested, but yes, you could theoretically display just the Timeline so long as it was nested in a Masher component for context. 

Another approach could be to build your own React component that directly utilizes the core moviemasher.js library. Specifically, its MashEditor class ultimately provides all editing functionality to the React components, including multi-level undo. The `add` *, `move` *, and `remove` * methods allow you to manage the content of the Mash.
