### ISSUE TITLE
Each segment of video starts at the beginning instead of specified time

### ISSUE THREAD

**Issue by Rafyfou** [moviemasher/moviemasher.js#36]
Hello,

There is a bug when I render a video.

If I split up the video into different segments, the result appear just fine in the video preview. However, when I render the video, each segment will start at the beginning of the video file instead.

**Comment by syntropo** [comment]
There are several known problems regarding rendering in the current version. In the coming weeks 5.1 will be released which should fix these and introduce a more simplified architecture for transforming and compositing clips.
