### ISSUE TITLE
How to install movie masher.js

### ISSUE THREAD

**Issue by mayank23er** [moviemasher/moviemasher.js#5]
i have download a zip , i am not able to identify how to run it?

**Comment by syntropo** [comment]
Check the README in angular-moviemasher, which utilizes moviemasher.js

**Comment by sonydaman** [comment]
In the documentation doesn't mention how to run?

**Comment by sonydaman** [comment]
Hi,

I pull the code and follow these step:
install git, npm, bower and grunt
npm install   (INSTALLING MODULES)
bower install --production --allow-root  (INSTALL DEPENDENCIES)
grunt   (CHECKING AND GENERATES FILE )

???????????????????  WHERE IS RUN COMMAND     ???????????????????????

============================================================
and i also download docker and follows these steps
docker-compose run --rm grunt
but getting error Cannot find suitable configuration file in this directory 
=============================================================



In the documentation doesn't mention how to run? 
Can you please tell how to run this application?
