### ISSUE TITLE
How to run the application 

### ISSUE THREAD

**Issue by sonydaman** [moviemasher/moviemasher.js#6]
Hi,

I pull the code and follow these step:
install git, npm, bower and grunt
npm install (INSTALLING MODULES)
bower install --production --allow-root (INSTALL DEPENDENCIES)
grunt (CHECKING AND GENERATES FILE )
# ??????????????????? WHERE IS RUN COMMAND ???????????????????????

and i also download docker and follows these steps
# docker-compose run --rm grunt
# but getting error Cannot find suitable configuration file in this directory

In the documentation doesn't mention how to run? 
Can you please tell how to run this application?

**Comment by syntropo** [comment]
The instructions will work if followed - please take a moment to read through them in their entirety. In this instance you're attempting to run the grunt utility instead of the application itself.

**Comment by sonydaman** [comment]
Kindly tell how to run

**Comment by syntropo** [comment]
You need to check out the README file in the angular-moviemasher project for detailed instructions on how to run.

https://github.com/moviemasher/angular-moviemasher

**Comment by sonydaman** [comment]
i tried but not able to run how can we run it?

**Comment by syntropo** [comment]
Please describe your actual problem and what you've done to expose it.

**Comment by sonydaman** [comment]
i install all application but in read me file there is no way to run the application.
Can you please tell how to run the application.

**Comment by syntropo** [comment]
Lifted directly from the README file:

cd into the angular-moviemasher/config/docker/production directory and execute:

`docker-compose up -d`
