### ISSUE TITLE
RUN APPLICATION ?

### ISSUE THREAD

**Issue by sonydaman** [moviemasher/moviemasher.js#7]
HOW CAN WE RUN THE APPLICATION ? 
# 

PLEASE LET ME KNOW THE STEP HOW TO RUN AFTER BUILD 
GRUNT COMMAND ......

**Comment by syntropo** [comment]
Again, you need to check out the README file in the angular-moviemasher project for detailed instructions on how to run. 

https://github.com/moviemasher/angular-moviemasher
