### ISSUE TITLE
frames bitmap files naming

### ISSUE THREAD

**Issue by think-01** [moviemasher/moviemasher.js#9]
Hi, I managed to set up everything with SQS, S3 and moviemasher transcoder API on AWS and its working fine untill I try to import a very short movie which results in less than 100 frame files on S3... in this case transcoder names files like 01.jpg, 02.jpg and so on but moviemasher.js still tries to poll 001.jpg, 002.jpg etc. how can I avoid that?

Also, when I'm rendering a movie from mash it gets uploaded to S3 without specifying a mime type ( which results in download from S3 link instead of showing movie ). How can I set a mime type in export data structure?

Thanks in advance!

**Comment by syntropo** [comment]
Hmm... is it always exactly 100 frames? You can specify the zeropadding property in the media element - to two, in your case.

And that's weird the mime type didn't make it through. You can specify the mime_type property of the output job element to override.

**Comment by think-01** [comment]
its not allways 100, thats the point it can be 50 and it can be 5000 frames, I cant forsee this thats why its a problem - ideally it would be that on import generated frame files are allways lets say 5 digits length ( with leading zeros ) but can I force this with import job?

**Comment by think-01** [comment]
okay I managed, I calculate zeropadding from callbacks videorate and duration :)
